/* eslint-disable no-unused-vars */

import { IUserBasicData, UserStatusTypes } from '../../../types/@autogenerated';

// TODO MICHEL regularizar para que este en este file

export type IFirebaseUser = {
  uid: string;
  email: string | null;
  displayName: string;
  appUserStatus?: UserStatusTypes;

  appRols: string[] | null;
  orgRols: string[] | null;
  userDefinedRols: string[] | null;
  enterpriseRols: any | null;

  avatar?: string | null;
};

export interface IUser extends IUserBasicData {
  appRols: string[];
  orgRols: string[];
  userDefinedRols: string[];
}
